# Generated by Django 5.1.3 on 2024-11-30 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quetion',
        ),
    ]
